"""Propose: generate auto-PRs from detected patterns.

Architecture guard: this skill edits the plugin's source files (appends to
`## Learned Patterns` sections). This is a genuine layering inversion and
lives in its own skill (`memory-proposer/`) — separated from `memory/` —
to make the inversion structurally visible.

Safety guardrails:
    - Always creates DRAFT PRs (never auto-merge)
    - Triple marker: --draft + `learned-pattern` label + HTML body comment
    - Content-hash branch names for idempotency (`bot/learned-pattern/<skill>-<hash>`)
    - Only appends to `## Learned Patterns` sections in skills/ or references/
    - NEVER touches agents/ (too sensitive — system prompts)
    - git worktree for clean PR branch (no cwd pollution)
    - All subprocess calls use check=True; specific exceptions caught at CLI boundary
"""

from __future__ import annotations

import hashlib
import json
import os
import pathlib
import shutil
import sqlite3
import subprocess
import sys
import textwrap
import time
from dataclasses import dataclass
from pathlib import Path

# Add memory skill scripts to path for db access
MEMORY_SCRIPTS = (
    Path(__file__).resolve().parent.parent.parent / "memory" / "scripts"
)
sys.path.insert(0, str(MEMORY_SCRIPTS))

from db import now  # noqa: E402


class ProposeError(RuntimeError):
    """Raised when PR generation fails."""


def _run(*args: str, cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    """Run a subprocess command with check=True, capturing output."""
    return subprocess.run(
        args,
        check=True,
        capture_output=True,
        text=True,
        cwd=cwd,
    )


def _pr_exists(branch: str) -> bool:
    """Check if a PR already exists for the given branch."""
    try:
        result = _run("gh", "pr", "list", "--head", branch, "--json", "number")
        data = json.loads(result.stdout or "[]")
        return len(data) > 0
    except (subprocess.CalledProcessError, json.JSONDecodeError, FileNotFoundError):
        return False


def render_pattern_content(
    *,
    pattern_id: int,
    summary: str,
    case_ids: list[int],
    avg_reward: float,
) -> str:
    """Render a Learned Pattern markdown block. Pure function."""
    case_list = ", ".join(f"#{c}" for c in case_ids[:10])
    if len(case_ids) > 10:
        case_list += f", +{len(case_ids) - 10} more"

    return textwrap.dedent(f"""
    ### Pattern {pattern_id}

    {summary}

    - **Cases:** {case_list}
    - **Avg reward:** {avg_reward:.2f}
    - **Detected:** {time.strftime('%Y-%m-%d', time.gmtime())}

    > This pattern was automatically detected from the case memory bank.
    > Review before accepting — remove if the pattern is noise or misleading.
    """).strip()


def render_pr_body(
    *,
    pattern_id: int,
    target_skill: str,
    case_ids: list[int],
    avg_reward: float,
) -> str:
    """Render the PR body markdown. Pure function."""
    case_bullets = "\n".join(f"- Case #{c}" for c in case_ids[:15])
    if len(case_ids) > 15:
        case_bullets += f"\n- ... +{len(case_ids) - 15} more"

    return textwrap.dedent(f"""
    <!-- generated-by: memory-pattern-detector v1 -->
    <!-- pattern-id: {pattern_id} -->

    ## Auto-Generated Learned Pattern

    This PR was generated by the `memory-proposer` skill from {len(case_ids)} cases
    with composite reward ≥ 0.6.

    ### Source Cases
    {case_bullets}

    **Average reward:** {avg_reward:.2f}

    ### Proposed Edit
    Append to `skills/{target_skill}/SKILL.md` → `## Learned Patterns` section.

    ### Review Checklist
    - [ ] Pattern is genuinely useful (not noise)
    - [ ] Content is accurate and actionable
    - [ ] No conflicts with existing skill guidance
    - [ ] Source cases actually support the pattern

    To reject: `gh pr close --delete-branch <this-pr>`.
    """).strip()


def _apply_to_skill_file(
    skill_md_path: Path, pattern_content: str
) -> None:
    """Append pattern content to the `## Learned Patterns` section of a SKILL.md file.

    Creates the section if it doesn't exist. Raises ProposeError if the target
    is outside the allowed directories (guardrail against touching agents/).
    """
    # Guardrail: refuse to edit files outside skills/ or references/
    parts = skill_md_path.parts
    if "agents" in parts:
        raise ProposeError(f"refusing to edit file under agents/: {skill_md_path}")
    if "skills" not in parts and "references" not in parts:
        raise ProposeError(f"refusing to edit file outside skills/ or references/: {skill_md_path}")

    existing = skill_md_path.read_text()
    marker = "## Learned Patterns"
    if marker not in existing:
        new_content = existing.rstrip() + "\n\n" + marker + "\n\n" + pattern_content + "\n"
    else:
        # Append after the existing section
        new_content = existing.rstrip() + "\n\n" + pattern_content + "\n"
    skill_md_path.write_text(new_content)


def generate_pr(
    conn: sqlite3.Connection,
    *,
    pattern_id: int,
    target_skill: str,
    summary: str,
    case_ids: list[int],
    avg_reward: float,
    repo_root: Path,
) -> str:
    """Generate a draft PR for a learned pattern.

    Returns the PR URL on success. Raises ProposeError on any failure.

    Idempotency: content-hash branch names. If a PR already exists for
    the same content hash, returns the existing PR URL without re-creating.
    """
    pattern_content = render_pattern_content(
        pattern_id=pattern_id,
        summary=summary,
        case_ids=case_ids,
        avg_reward=avg_reward,
    )

    digest = hashlib.sha256(pattern_content.encode()).hexdigest()[:8]
    branch = f"bot/learned-pattern/{target_skill}-{digest}"

    # Idempotency check
    if _pr_exists(branch):
        # Return the existing PR URL
        try:
            result = _run(
                "gh", "pr", "view", branch, "--json", "url", "-q", ".url"
            )
            return result.stdout.strip()
        except subprocess.CalledProcessError as exc:
            raise ProposeError(f"PR exists but lookup failed: {exc}") from exc

    # Fetch origin/main
    try:
        _run("git", "-C", str(repo_root), "fetch", "origin", "main")
    except subprocess.CalledProcessError as exc:
        raise ProposeError(f"git fetch failed: {exc.stderr}") from exc

    # Create git worktree for the PR branch (keeps cwd clean)
    wt_name = branch.replace("/", "-")
    wt_path = Path(f"/tmp/memory-pr-{wt_name}")
    if wt_path.exists():
        shutil.rmtree(wt_path, ignore_errors=True)

    try:
        _run(
            "git",
            "-C",
            str(repo_root),
            "worktree",
            "add",
            str(wt_path),
            "-b",
            branch,
            "origin/main",
        )
    except subprocess.CalledProcessError as exc:
        raise ProposeError(f"git worktree add failed: {exc.stderr}") from exc

    try:
        # Apply the edit
        skill_md = wt_path / "skills" / target_skill / "SKILL.md"
        if not skill_md.exists():
            raise ProposeError(f"target skill not found: skills/{target_skill}/SKILL.md")

        _apply_to_skill_file(skill_md, pattern_content)

        # Commit
        try:
            _run("git", "-C", str(wt_path), "add", str(skill_md.relative_to(wt_path)))
        except subprocess.CalledProcessError as exc:
            raise ProposeError(f"git add failed: {exc.stderr}") from exc

        commit_msg = textwrap.dedent(f"""\
            chore(memory): add learned pattern to {target_skill}

            Detected pattern {pattern_id} from {len(case_ids)} cases.
            Avg reward: {avg_reward:.2f}

            Generated-By: memory-pattern-detector
            Pattern-Ids: {pattern_id}
            Case-Ids: {",".join(str(c) for c in case_ids)}
            """)

        try:
            _run("git", "-C", str(wt_path), "commit", "-m", commit_msg)
        except subprocess.CalledProcessError as exc:
            raise ProposeError(f"git commit failed: {exc.stderr}") from exc

        # Push
        try:
            _run("git", "-C", str(wt_path), "push", "-u", "origin", branch)
        except subprocess.CalledProcessError as exc:
            raise ProposeError(f"git push failed: {exc.stderr}") from exc

        # Create the draft PR
        pr_body = render_pr_body(
            pattern_id=pattern_id,
            target_skill=target_skill,
            case_ids=case_ids,
            avg_reward=avg_reward,
        )

        try:
            result = _run(
                "gh",
                "pr",
                "create",
                "--draft",
                "--base",
                "main",
                "--head",
                branch,
                "--title",
                f"[auto] Learned pattern for {target_skill}",
                "--body",
                pr_body,
                "--label",
                "automated,learned-pattern",
            )
        except subprocess.CalledProcessError as exc:
            raise ProposeError(f"gh pr create failed: {exc.stderr}") from exc

        pr_url = result.stdout.strip()

        # Update the patterns table
        conn.execute(
            """
            UPDATE patterns
            SET pr_url = ?, pr_branch = ?, status = 'proposed', updated = ?
            WHERE pattern_id = ?
            """,
            (pr_url, branch, now(), pattern_id),
        )

        return pr_url

    finally:
        # Clean up worktree (branch stays pushed)
        try:
            _run(
                "git",
                "-C",
                str(repo_root),
                "worktree",
                "remove",
                str(wt_path),
                "--force",
            )
        except subprocess.CalledProcessError:
            # Best effort cleanup
            if wt_path.exists():
                shutil.rmtree(wt_path, ignore_errors=True)
